language: groovy
jdk:
- oraclejdk8
before_script:
- chmod +x grailsw
script: ./grailsw clean && ./grailsw test-app && ./grailsw war dev
before_cache:
 - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
 directories:
 - $HOME/.gradle/caches/
 - $HOME/.gradle/wrapper/