language: groovy
sudo: false
install: true
addons:
  sonarcloud:
    organization: "neftalyluis-github"
    token:
      secure: "qsxLR8ECp7gYkfp6cKsBmuCYcDcptaDzLSsGyVf+Jul2dgyD68DCYFQQM2jq7F+AL/8YsT/LvFCJcHvCgzyTMTIEDDbN2fHW4+iFMw3U9i4RLcY/ejEOTsFJ6EsVaquUNCOz+3RiXmo8lvwnVL3/EP2vva2aVriLfeJxCY3GB9P/oCf8N4gkxnoVb3txN+ZAApebK/1FqXZ6YMGlmUOy8Z1Ww1V563ARNFb4hOrZOvOzO/sp/sDC/K5vUskg1hzgnB51iUb2pqN1sMaKt5NDEnFLMZBJgVpJ3AisFoWkh5LfD1LyoH/8Jcz2vazCN7CU3vVhcGk0yyDOfDL0v04A3ydvBHt1N1mz6w9xSXWU6/iTSHZogSfgHsBDdfjY0BTbAfQ6I4j7MrFGHCWnjTf/V3B5fIHXTwjAsuy7PX9mWHwCumbUgF4+7qsFYCkAWFQdrfhT8l8nNMW+vFlBR11zk2hs2mFqOxBe4xCAyazlSgxqErtFv4KkZUB+9EunOqorBGj7OgozvosOX3mmH2WfcCiNY9jLxZXXdK3KluRqvlW13PpT+HdiomDFEZrIsoP3moBfxALUQ1RYlZ6fUah88YT6mEnPnuZhnwjcWCkCOC5atKn2XxTOuFMffmJLy2Cyif6YYsDLaJdQoKD33Kzs4WFG/cO9/itkpEM0b0lr3ko="
jdk:
 - oraclejdk8
before_script:
 - chmod +x grailsw
script:
 - ./grailsw test-app
 - ./grailsw dev war
 - ./gradlew sonarqube
before_cache:
 - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
 - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
 directories:
   - '$HOME/.m2/repository'
   - '$HOME/.sonar/cache'
   - '$HOME/.gradle'
   - '.gradle'