language: groovy
sudo: false
install: true
addons:
  sonarcloud:
    organization: "neftalyluis-github"
    token:
      secure: "qsxLR8ECp7gYkfp6cKsBmuCYcDcptaDzLSsGyVf+Jul2dgyD68DCYFQQM2jq7F+AL/8YsT/LvFCJcHvCgzyTMTIEDDbN2fHW4+iFMw3U9i4RLcY/ejEOTsFJ6EsVaquUNCOz+3RiXmo8lvwnVL3/EP2vva2aVriLfeJxCY3GB9P/oCf8N4gkxnoVb3txN+ZAApebK/1FqXZ6YMGlmUOy8Z1Ww1V563ARNFb4hOrZOvOzO/sp/sDC/K5vUskg1hzgnB51iUb2pqN1sMaKt5NDEnFLMZBJgVpJ3AisFoWkh5LfD1LyoH/8Jcz2vazCN7CU3vVhcGk0yyDOfDL0v04A3ydvBHt1N1mz6w9xSXWU6/iTSHZogSfgHsBDdfjY0BTbAfQ6I4j7MrFGHCWnjTf/V3B5fIHXTwjAsuy7PX9mWHwCumbUgF4+7qsFYCkAWFQdrfhT8l8nNMW+vFlBR11zk2hs2mFqOxBe4xCAyazlSgxqErtFv4KkZUB+9EunOqorBGj7OgozvosOX3mmH2WfcCiNY9jLxZXXdK3KluRqvlW13PpT+HdiomDFEZrIsoP3moBfxALUQ1RYlZ6fUah88YT6mEnPnuZhnwjcWCkCOC5atKn2XxTOuFMffmJLy2Cyif6YYsDLaJdQoKD33Kzs4WFG/cO9/itkpEM0b0lr3ko="
  apt:
      packages:
          - sshpass
jdk:
 - oraclejdk8
before_script:
 - chmod +x grailsw
script:
 - ./grailsw test-app
 - ./grailsw dev war
 - ./gradlew sonarqube
before_cache:
 - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
 - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
after_success:
   - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && export SSHPASS=$DEPLOY_PASS
   - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && sshpass -e scp -o stricthostkeychecking=no build/libs/course-manager-0.1.war $DEPLOY_USER@$DEPLOY_HOST:$DEPLOY_PATH
env:
    global:
      - secure: "hODSzwMl9TCHTogdEu2XvVPeA48CuGxT8KxMCTOiWrE9WSLx/7bFDyykTBlaotSgZesiy3GzTKZ689U07GDBIm4QBU5zeSeaddM8QUcbaaw/Cuwn9URZD+Xs3H0fo/9QN6zUpFDnKzI6pnzMAe47ldDtziUM8XgkgD6xsqisy7vv4Fw7qrUmG9uBTBRy+GAJjT14pyR30AyzSzSh+6jWT1Fa1zDsw2hpEf056TFScsc2WINJ/ltqIOV/+X4bJgqATJ9sSKWaY6ZjKoSA/Rk8BpV13irOhJbMX4kDr88vVNsGC1038hV6cEz3Rie0kFWSCIW668Dls22WWJuxLw7vGd4KAFtZvEIvQWrRJ3PBcDpYtj70VefTtOOYzYO7oca5ZcwjqK20j7dJWwLdzi8+pMgjhhVjwpHr7RLhJPAOdgVqkcM3fib56HD0iDWC/hLsMJUqVTpbq+aJTGMFk4L+6xuGPsqx1mt6Mucxzy0qmByoGVd9xDZnhPQds4SLTi1TgaBhwl1PkuGe3a1xhuzKm5UVCwvQ1vy3vfSldl3s/TXmjksENQBMvjR+pf3TKiEBW87K6iI+qOpskKVdSEW8RQ3hYOpqTfQB8GssVXAC+2mWIV2R6i38MNRZFre5aG/A0xa9gl+kum5O53miNwh+6PAU6WeMQxDlxFObyTKEruA="
      - secure: "lTt/+Rts8/Ih0OGQySCtssmrICezRMO5FZFidYkeEk3amSpLJU5C5ql5AnwpWMI/ijqANqFez73DiG1RefkrfMYE4axOTcnSMG/zvyFblZJFw4mHlVCBwZCW7HO9YEJCP5qHj8EFjD27Ki9sfkP+tVvfsRnc6g/fGuCm1K3wCMWokfybj6piqEXm2tlWH+pPF+6pxjxI5XXRvAiH7gnkhYIJ0Br5XEYal6SS2AQAKXX2J1F5RHug7oe86gHBrhXW4fn+9taWy+tvNwHoEhmtrQ2mV5Bx/Wt21f/dMLzz61+RXLg2XzKPGkC3j2suMwmg6BkEAOsUrB230nPtoRm6R21TMG8BjboKqZ7RdurMFCHhgJpnQrlo8coLKZP5YePNhj1nEU0X0R/d1ud4Kz0KQUkrPaXl4A3SWZ3/jZnV7jZT06q3/9dfbqRsmQLBJ3KKY3odq2bI1ZMT4bDDVIvZR5CjJOFs7OlL6tydTuV71aJne/N6ZoFuYuh6QIU3okN8pKSBn9ZzOpRfpHyZvgZYEHOlChP6KhBEWKOcmUHzjoMb8BuG+ogh1zsdLjyLqYyO8Hq5JX7E9ogMTDBxGFNm0cAq6pLqv8UY0YvIqAWgW1PJ4naGf3t5/eEdTJSMzTxXYZuF765GXNt+qAabi3CV8gFBDry0UhWN9TELCVHb/e4="
      - secure: "x1KE2Ner8RxsFMOcQUkb7bewgwL5UxzXsB5bHV/lBkBgcj+CKnI7djO28eAOvotjbCQvJpRpiv96IyOUY0kBUwIAAJipFSwsxsVuJnyB7tM923grcvcemK0/Y8IL1OX1pF9N63TmRWYSfWwehfb1PguDdvsl6fB1ZWLIUyHZx4f8ptcIjcgQx7I3bwExzbzxaedP44ODTRTVhH2q5UqJXbDgjX0yVI+6y8uK7RJ+Y2ECeL1+bqbVCHZJ19hUu6sz3KXUQ9kPK1Gw34lx75JkOKywj+wWZcbEoARVC/hkxpkmV8lCaZ6adjoJ2DD/APf+HDflXXp1WUcV1cNoWgJt1SKKiG9I1AuDazJloH+kMqgqtVTqGD1/57BmpPs6ma5N1IUWSZohO9dk8tIcnxM/XiKIgMPy4gPXaq07rJbYghc5k2e3HIlWfI26MMoELMz3k6Z3ZByI0Y9+ii66pOjH9WYW90fgytiaRD4pKxG8T9J2/U8uT1RyLl5tWIlKWcsl3/OUf6BYKq1DRCFLqdHTgql0K4hGms0yV4G7Rgjgb/v/kfZRI6aoEldKacl+r1FzslTNwOqdncSY+UxQXMzvVQh/LUFRSbigX6gy6wZ0sVEUxEerDmXpEAOym3EK9DSwTfVtCgu14fY8/TKYwrE7hOaOcNk4yBbhibgbUDSHKR0="
      - secure: "n77zfbYhxr7V3O/2DgHSDslUkiBroxfvPMK4JYrGL/eXH/Zcb6YCdPlaajOjFyH5Il7+cXJZwd8mvyH4xU/5bshEoOck8O9xH3RgIkaChmCuZ9g1IncJo/3MEkHwkXOkn8Zs3ZEklBC3Uf+HrPe7LRJmGKquoZN3RCkYbTJ+dm8Su99wgSvAaZG2fGGQY4SmTEQ/LCiPvm6fkvuYZKnRM0E7/GcPZ7dvMbLfp3nFbokNdNovpq6aJ0FKVVje8OWaq8Bb39mkomWDXByA65q5lpZGYGy8Xl+kjtvW81TCJFeQjhHNz3/v67XxjvaH2O2LN1YFJv/AEdldA8/IZ65LHasumC1TKeAGjMnd39la+63tDapW6C7ljfBoAN17WTjqxrgF6xYLzsREeI00Xp0rDlBns2xrMpjQ4UhOCtkWMjDaPq9hdAkP1FO0KDqgMdX215k1xL/VEOs3fpOWs/kvNqGYFNE9pj6UbpDQL5r0+3CfFknh1WmGWeJDTU1mbAF5zW0lLsrI7vRCsWdXNXh6DpAEKoOc9AgEoB3yMjaRjK/IsE4dbxGplijVLM9H6FLkM/22tW0FOUHMhI78YQ9Y1Ha2/NV/QJmw/fOP6h0h7SGPWy+X/8gSyyk70Cdx1eTX2RObzMxv1iMpNEX7AhIGEKgjNLmvmWgzvNs+Tpfjqz8="
cache:
 directories:
   - '$HOME/.m2/repository'
   - '$HOME/.sonar/cache'
   - '$HOME/.gradle'
   - '.gradle'